
# Write your query or mutation here

query home {
  items {
    home {
      identity_image {
        id {
          id
        }
      }
      identity_image_theme_alternate {
        id {
          id
        }
      }
      hero_image_theme_alternate {
        id {
          id
        }
      }
      hero_image {
        id {
          id
        }
      }
      hero_image_transitioned_theme_alternate {
        id {
          id
        }
      }
      hero_image_transitioned {
        id {
          id
        }
      }
      id
      identity_text_background {
        id {
          id
        }
      }
      identity_text_background_theme_alternate {
        id {
          id
        }
      }
      cta_wave_illustration {
        id {
          id
        }
      }
      cta_wave_illustration_hover {
        id {
          id
        }
      }
      heading
      hero_text
      skills_heading
      skills_text
      work_heading
      work_text
      info_text_start
      info_text_end
      cta_button_text
      cta_text
      availability_text
      scroll_icon {
        name
        icon {
          id {
            id
          }
        }
      }
    }
  }
}

